# Generated by Django 4.0.4 on 2022-06-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_consumer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
