# Generated by Django 4.0.4 on 2022-06-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_consumer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
