# Generated by Django 4.0.4 on 2022-06-23 12:53

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_consumer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='photo',
            field=models.ImageField(null=True, upload_to=account.models.user_directory_path),
        ),
    ]
