# Generated by Django 4.0.4 on 2022-06-24 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_consumer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='photo',
        ),
    ]
