# Generated by Django 4.0.4 on 2022-05-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('units', models.CharField(choices=[('Wh', 'Wh'), ('kWh', 'kWh'), ('mWh', 'mWh')], max_length=10)),
                ('kg_co2eq', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source_iata', models.CharField(max_length=3)),
                ('destination_iata', models.CharField(max_length=3)),
                ('cabin_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], max_length=10)),
                ('source_name', models.CharField(max_length=100)),
                ('destination_name', models.CharField(max_length=100)),
                ('kg_co2eq', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('diesel', 'diesel'), ('gasoline', 'gasoline'), ('petrol', 'petrol'), ('butane', 'butane'), ('natural_gas', 'natural_gas'), ('propane', 'propane'), ('kerosene', 'kerosene'), ('fuel_oil', 'fuel_oil'), ('gas_oil', 'gas_oil')], max_length=15)),
                ('value', models.FloatField()),
                ('units', models.CharField(choices=[('tonnes', 'tonnes'), ('liters', 'liters'), ('gallons', 'gallons'), ('uk_therms', 'uk_therms'), ('us_therms', 'us_therms'), ('MMBtu', 'MMBtu'), ('cubic_meters', 'cubic_meters')], max_length=15)),
                ('kg_co2eq', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=10)),
                ('food_products', models.CharField(max_length=255)),
                ('kg_co2eq', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.PositiveSmallIntegerField()),
                ('distance_unit', models.CharField(choices=[('km', 'km'), ('miles', 'miles')], max_length=10)),
                ('fuel_efficiency', models.PositiveSmallIntegerField()),
                ('fuel_eff_unit', models.CharField(choices=[('mpg', 'mpg'), ('km/l', 'km/l'), ('1/100km', '1/100km')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'gasoline'), ('diesel', 'diesel')], max_length=10)),
                ('kg_co2eq', models.FloatField()),
            ],
        ),
    ]
