# Generated by Django 4.0.4 on 2022-05-20 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='record.user'),
        ),
        migrations.AddField(
            model_name='flight',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='record.user'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='record.user'),
        ),
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='record.user'),
        ),
        migrations.AddField(
            model_name='transport',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='record.user'),
        ),
    ]
