# Generated by Django 4.0.4 on 2022-05-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_electricity_user_flight_user_fuel_user_meal_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
