# Generated by Django 4.0.4 on 2022-05-23 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('record', '0004_remove_electricity_user_remove_flight_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='consumer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='account.consumer'),
        ),
        migrations.AddField(
            model_name='flight',
            name='consumer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='account.consumer'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='consumer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='account.consumer'),
        ),
        migrations.AddField(
            model_name='meal',
            name='consumer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='account.consumer'),
        ),
        migrations.AddField(
            model_name='transport',
            name='consumer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='account.consumer'),
        ),
    ]
